version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: employee_ui # specify the directory of the Dockerfile
    container_name: angular
    ports:
      - "4200:4200" # specify port forwarding
    links:
      - express

  express: #name of the second service
    build: employee_mongo_node # specify the directory of the Dockerfile
    container_name: express
    ports:
      - "4201:4201" #specify ports forwarding
    links:
      - database

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
